version: "3.9"

services:
  evomind:
    build: .
    container_name: evomind

    environment:
      EVOMIND_OTEL_EXPORTER_ENDPOINT: 192.168.65.254:4317
      EVOMIND_OTEL_ENABLED: "true"
      EVOMIND_DATABASE_PATH: /data/evomind.db
      EVOMIND_DEBUG: "true"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "8001:8000"

    volumes:
      - evomind-data:/data

volumes:
  evomind-data:

networks:
  default:
    name: evomind-net
    driver: bridge